# Generated by Django 5.0.6 on 2024-07-28 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='UnidadEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Unidades Educativas',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.curso')),
            ],
            options={
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(default='', max_length=200, verbose_name='Correo electrónico personal')),
                ('tipo', models.CharField(choices=[('alumno', 'Alumno'), ('padre', 'Padre'), ('profesor', 'Profesor'), ('administrador', 'Administrador')], max_length=18)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unidad_educativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.unidadeducativa')),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padres', to='chat.persona')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='chat.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.materia')),
                ('alumno', models.ForeignKey(limit_choices_to={'tipo': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, to='chat.persona')),
            ],
            options={
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_academico', models.IntegerField(blank=True, null=True, verbose_name='Año Académico')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.curso')),
                ('alumno', models.ForeignKey(limit_choices_to={'tipo': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, to='chat.persona')),
            ],
            options={
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'tipo': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, to='chat.persona'),
        ),
        migrations.AddField(
            model_name='curso',
            name='unidad_educativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.unidadeducativa'),
        ),
    ]
